import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Avsora Software",
  description: "Enterprise SAP Solutions Company",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav style={{ padding: "20px", borderBottom: "1px solid #eee" }}>
          <Link href="/" style={{ marginRight: "20px" }}>
            Home
          </Link>
          <Link href="/about" style={{ marginRight: "20px" }}>
            About
          </Link>
          <Link href="/contact">
            Contact
          </Link>
        </nav>

        {children}
      </body>
    </html>
  );
}







// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
